platform :ios, '8.0'
use_frameworks!
target 'HebcaLog' do
#pod 'BmobSDK'
pod 'AVOSCloud'               # 数据存储、短信、云引擎调用等基础服务模块
pod 'AVOSCloudIM'             # 实时通信模块
pod 'AVOSCloudCrashReporting' # 错误报告模块
pod 'QMUIKit'
pod 'IQKeyboardManager'
end
